[package]
name = "subdomain_distribution"
version = "0.1.0"

[dependencies]
starknet = "2.1.0-rc2"

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true

# Enable CASM codegen.
casm = true

# Emit Python-powered hints in order to run compiled CASM class with legacy Cairo VM.
casm-add-pythonic-hints = true
